### ISSUE TITLE
refactor all variables and functions (except class definitions) to use camelCase

### ISSUE THREAD

**Issue by nickjanssen** [ironbane/IronbaneServerLegacy#103]
Could we automate this somehow?

**Comment by ingmargoudt** [comment]
could be picked up during transition to v0.3?

**Comment by nickjanssen** [comment]
Tried it using a regex, see camelcase branch. But a lot of stuff is broken...man so annoying. I think it's better to replace things by hand gradually.

**Comment by ingmargoudt** [comment]
closing this issue. Refactor code, with respect to casing, along the way
