### ISSUE TITLE
Finish Graveyard

### ISSUE THREAD

**Issue by samjar** [ironbane/IronbaneServerLegacy#109]
Finish the graveyard area. 
1. Road throughout the graveyard (90%)
2. Undead Dungeon - Exterior (80%)
3. Undead Dungeon - Interior (0% - still drawing blueprints)
4. Alabaster Tomb - Interior (0% - still drawing blueprints)
5. Place graves and fences (0% - I have to finish modeling the area before models can be placed)
6. Skeleton Slime Dungeon (0% - still drawing blueprints)
7. Graveyard Maze (50% - need to add a few constructions within the maze, as well as finish placing models)
8. Church - Interior (0% - need seats and an altar)
9. The Abyss - (0% - still drawing blueprints)
10. Entrances to U.D (50% - two more holes and 4-5 more entrances)
11. Place Bosses and Monsters(0% - have to finish modeling before they can be placed)
12. Make keys (20%)

**Comment by nickjanssen** [comment]
FYI you can make checkboxes like this, and then check them afterwards to keep track:
- [ ] Item done 1
- [ ] Item done 2

```
- [ ] Item done 1
- [ ] Item done 2
```
