### ISSUE TITLE
About / Home Page

### ISSUE THREAD

**Issue by bsparks** [ironbane/IronbaneServerLegacy#12]
decide whether or not the About / Home page should be a dynamic Markdown page or a regular Angular view and create it. Pull in the News forum for the front page listing (angular directives). Currently it is its own view, "home".

**Comment by ingmargoudt** [comment]
I would like to be assigned on this issue. It's simple compared to server work, so good for me to catch up with AngularJS :)
In the database there are two tables: bcs_articles and bcs_pages. Which serves what purpose?

**Comment by bsparks** [comment]
im not sure how to assign you unless you are an official member of the org, will have to figure that out with Nick...

as far as the tables, bcs_pages is the original table that may have once been for a similar purpose. I think at this point we can prolly drop it.

**Comment by bsparks** [comment]
In regards to your irc comment, the articles are admin only and unlike the forum posts the are in markdown. The articles are also being implemented using ng-include so they should have the full power of angular inside. Ng-include is executed within a child scope of the parent page. So, that being said I would create a directive that lists the news from the forum.

If you need me to do that part to see what I mean I can, just do the image part.

**Comment by ingmargoudt** [comment]
fixed for 0.4
