### ISSUE TITLE
"Please login first" right after logging in and trying to play

### ISSUE THREAD

**Issue by nickjanssen** [ironbane/IronbaneServerLegacy#127]

**Comment by bsparks** [comment]
this is because the socket connection is already connected prior to logging in, I'm working on getting that fixed.

**Comment by nickjanssen** [comment]
Circumvented for now, see 1b482b08595a115c3bb612785d97d7d6e3cc4571

**Comment by ghost** [comment]
I believe this was fixed a long while back, or at least is not a current issue. This can be reopened if needed.
