### ISSUE TITLE
Auto convert *.obj to *.js with grunt using the exporter

### ISSUE THREAD

**Issue by nickjanssen** [ironbane/IronbaneServerLegacy#128]

**Comment by nickjanssen** [comment]
We need to execute a command on every .obj file, don't know if this is possible with grunt.

Would be really cool though for Sam, he can just throw in OBJs and they get auto converted. Maybe a watch task can be helpful too

**Comment by ingmargoudt** [comment]
https://github.com/makesites/grunt-three-obj

**Comment by nickjanssen** [comment]
Working mostly now thanks to @ingmargoudt 's suggestion. Some OBJs generate errors though, such as the ones from the terrain. Not sure why yet.

**Comment by nickjanssen** [comment]
Some models generate errors because they have faces with two vertices, don't know how that is possible. @samjar if the models are not loading you can try loading the OBJ in Meshlab, and it will complain whether there are faces with two vertices present or not. Can you maybe check for that directly from Blender?

See makesites/grunt-three-obj#7

**Comment by nickjanssen** [comment]
0e079dea8367f0759f9c7430b2d71a4fb1d6230d
