### ISSUE TITLE
add basic swearing filter

### ISSUE THREAD

**Issue by nickjanssen** [ironbane/IronbaneServerLegacy#133]

**Comment by bsparks** [comment]
I think we should create an angular filter on the output that converts the messages to "I think you're full of ****!" , this way we could allow the end user to configure whether or not to do this filtering. It would mean however that the actual swears would be sent across the wire, but I think that might be OK, at least for a quick v1.

**Comment by nickjanssen** [comment]
They still show up in the chat balloons :D
