### ISSUE TITLE
using a very long username for login gives a weird error

### ISSUE THREAD

**Issue by nickjanssen** [ironbane/IronbaneServerLegacy#139]
![screen shot 2013-08-06 at 10 45 47 pm](https://f.cloud.github.com/assets/2780160/920236/4d32d606-fed9-11e2-9dc2-54d53c9fe921.png)

**Comment by ingmargoudt** [comment]
isnt that just when you enter an empty password?

**Comment by ingmargoudt** [comment]
looks like the line of code responsible for this is:

src\server\http\routes\user.js:14

**Comment by ingmargoudt** [comment]
resolved in commit 08202d4
