### ISSUE TITLE
use  nodejs graphicsmagick

### ISSUE THREAD

**Issue by ingmargoudt** [ironbane/IronbaneServerLegacy#154]
Currently images are created by php calls on graphicsmagick. Since we want to migrate out of Apache, those images should be generated by some other process. There is a graphicsmagick implementation for node.

Look at:

http://aheckmann.github.io/gm/

**Comment by bsparks** [comment]
just in case this wasn't clear, we are already using that, the php urls are just faked, no actual php is involved.
