### ISSUE TITLE
Wooden Helmet updates pants instead

### ISSUE THREAD

**Issue by nickjanssen** [ironbane/IronbaneServerLegacy#164]
Give yourself a wooden helmet and wear it. It will show you are wearing pants suddenly

**Comment by ingmargoudt** [comment]
Strange...it is certainly marked as a head item in the database..

**Comment by bsparks** [comment]
must be a bug in the graphics magick rendering then (where it builds the sprites)

**Comment by nickjanssen** [comment]
did not appear anymore for me, might have been an issue with the cache
