### ISSUE TITLE
testing session

### ISSUE THREAD

**Issue by nickjanssen** [ironbane/IronbaneServerLegacy#169]
- [x] cheese should have 5 health points
- [x] holding spacebar is annoying: second time does not jump
- [x] when you touch ground and jumptimer > 1 second set it to 0?
- [x] bow shooting sound sometimes not working 
- [x] slime turrets need something where they shoot from
- [x] guest login no longer working
- [x] add rat boss!
- [x] add torches when you leave the tutorial: entrance to the main world
- [x] aim on NPCs
- [x] disable raycasting for the camera on NPCS
- [x] lights still not applied everywhere, e.g. on objects that are added after the lights were added!

@samjar can you make the transition from the tutorial cave entrance to the ground less steep and more clear?
I have found that people usually get stuck or just fall down instead of following the path
- [x] monsters are buggy, show random question marks and sometimes stop seeing you for no reason
- [x] it is possible to get stuck in a bridge
- [x] fall through terrain
- [x] movable obstacles missing
- [x] rats can come out of nowhere when you are in the tutorial zone at the bottom, where the jump challenges are
- [x] jumping in the area with the jump challenges sometimes teleports your chart to the ceiling
- [x] at the login screen: if you type something and then delete a letter it removes the whole input
- [x] after you kill NPCs they seem to suddenly ghost-move towards your position
- [x] model painter: tile selection box not working
- [x] paintings not working, would be very cool if they could be chosen a texture using the editor
- [x] when you go back to the main menu the preview position is suddenly different
- [x] bunnies walk in the ground
- [x] character creation screen mac os arrow bug
- [x] previous arrow does not do anything, should switch to last look attr
- [x] instead of turning off the daylight at night, make it blue to the terrain does not look undefined, like morrowing/oblivion
- [x] wow style standingOnUnits, as if standing on terrain
- [x] moving rapidly between cells stops some objects from loading
- [x] moving objects blenderstyle does not copy painted properties
- [x] signs text are not rotated properly
- [x] opacity not working for particles
- [x] check firefox/ linux
- [x] ghost mode
- [x] [9/25/13 10:45:02 PM] ingmar.goudt: 11
  Uncaught Error: ERROR: Quaternion's .setFromEuler() now expects a Euler rotation rather than a Vector3 and order.  Please update your code.
  [9/25/13 10:45:13 PM] Nick Janssen: when?
  [9/25/13 10:45:25 PM] ingmar.goudt: rotating a mesh
  [9/25/13 10:45:30 PM] ingmar.goudt: a building
  [9/25/13 10:45:33 PM] ingmar.goudt: in the editor

Will be postponed:
- [ ] the night is ugly and needs stars. The world at night looks uninteresting
- [ ] implement light mapping
- [ ] add all models made by 3d modelers, also on forums (whats wrong with the statue?)
- [ ] shadows in dungeons
- [ ] cookie set for a month not working, still forgets login sometimes? (needs more testing)
- [ ] arrows seems to keep raycasting even after landed
- [ ] female sprites' eyes need two pixels in height
- [ ] it is possible to register multiple accounts with the same name :P
- [ ] transparent sprite show the loading text behind webgl canvas?
- [ ] world entrance surrounding area: add monsters, too boring currently. guide the players what to do there. 
- [ ] town is a ghost town: no npcs; nothing is happening and super boring. houses are empty... needs a lot of work
- [ ] houses all look the same

**Comment by bsparks** [comment]
about the cookie issue, the php site and game are not in sync with those sessions I don't think. that might be it. once the site's in angular they should be synced up.

**Comment by LaoDengy** [comment]
Meet the same problem, English is not very good, collapse
