### ISSUE TITLE
method design issue

### ISSUE THREAD

**Issue by ingmargoudt** [ironbane/IronbaneServerLegacy#171]
This issue has an example but can apply to any similar scenarios.

Scenario:
When you open the forums, and go to a board, you get a list with all topics of that board. On the server, the (static) method Board.getTopics(boardID) is called. Now this method actually returns the variables that are needed for the board-view, consisting of a difficult query with joins and subselects. 
But: There could be a scenario where just the Topic objects are required, so with a Select \* from forum_topics. Should we make 2 methods, one for the view and one for general data retrieval?

**Comment by bsparks** [comment]
yes I was thinking about the home page and having a specialized topic getter that contains only the first post of each topic. so I think that there prolly needs to be other methods, OR added config params that allow you to get more information. OR maybe its better to just combine 2 or more Service calls (multiple queries, sorting / manipulation on the back end)

also, speaking of the front page, I wonder if the "News" section should be more of an Article w/ comments style (or maybe no comments) than forum board.
