### ISSUE TITLE
Investigate ghost mode

### ISSUE THREAD

**Issue by nickjanssen** [ironbane/IronbaneServerLegacy#172]
`Ghost mode is a glitch where you cannot see objects such as chests, signs, NPCs, and other players. 
Nothing but chat.`

See http://www.ironbane.com/forum.php?action=topic&topic=851

**Comment by Kadajett** [comment]
Going to try and take a crack at it. After I get the server set up. Wish me luck.

**Comment by nickjanssen** [comment]
as mentioned by a forum member here: http://www.ironbane.com/forum.php?action=topic&topic=909
finally reproducable!

**Comment by nickjanssen** [comment]
Possibly fixed in 477955ac4d3226eef2d67e66e25ac46b623744de but this only fixes a client issue when you go back to the main menu. Others complained that ghost mode was still there when you refresh or even relogged. Closing for now until we have new fresh reports of this bug in 0.4
