### ISSUE TITLE
random names are dark green in the chat

### ISSUE THREAD

**Issue by nickjanssen** [ironbane/IronbaneServerLegacy#173]
Reported by a forum member, but I also have seen this myself a few times. I think it occurs in the Players online message, but needs further investigation.

**Comment by ingmargoudt** [comment]
In src\client\game\js\ng\chat.js:40

<span ng-repeat="user in data.online" class="name {{user.rank}}" ng-class="{delim: !$last}">{{ user.name }}</span></div>'

I think whenever class="name {{user.rank}} has no entry in the css file then the default color is shown.

**Comment by bsparks** [comment]
here: https://github.com/ironbane/IronbaneServer/blob/master/src/client/game/css/ironbane.less#L253

if there is no rank for the user, we can add a top level class for just .name {color: ?} but what color are they supposed to be?
