### ISSUE TITLE
Terrain auto-smooths after next login

### ISSUE THREAD

**Issue by samjar** [ironbane/IronbaneServerLegacy#177]
When I uploaded the new map, the terrain was jagged, pointy, pixel-ated and all that. When I re-logged (I think that's what caused it; to be honest, I wasn't really paying attention), it had all smoother back out again. Will investigate further.

**Comment by nickjanssen** [comment]
probably duplicate of #93 ?

**Comment by samjar** [comment]
Yup! Sorry, didn't know there was one of these already haha

**Comment by nickjanssen** [comment]
No worries :) You can search issues using the searchbar at the top
