### ISSUE TITLE
Cave of Darkness

### ISSUE THREAD

**Issue by samjar** [ironbane/IronbaneServerLegacy#189]
Just a quick prototype of how the Cave of Darkness will work. I tried to draw certain tiles that blended in with the darkness, but it didn't work out too well. In Cube Projection I had to change the Cube Size and a few more things. I think that's why it wouldn't load correctly. For now, I'm just gonna leave the blending for another time. Instant darkness as soon as you get past a certain point in the cave.

![caveofdarkness](https://f.cloud.github.com/assets/4355906/1083062/cc9e1fe8-1592-11e3-80b9-46e05d54699f.png)

![caveofdarkness2](https://f.cloud.github.com/assets/4355906/1083064/d2331774-1592-11e3-8593-7a3f3a90f58a.png)

The idea, by the way, is that you're not supposed to be able to see anything but yourself, other players, NPC's and an occasional piece of terrain, illuminated by a torch. It'll be fun watching people stumble around, falling off cliffs, running into walls. There's endless possibilities!

**Comment by nickjanssen** [comment]
Interesting…how about making the cave completely dark (a zone setting) and creating a torch item which they can carry around? So players would be wise not to enter without torches!

**Comment by bsparks** [comment]
is there a way to have some light shining in from the cave entrance at least?

**Comment by nickjanssen** [comment]
haha of course ;)

**Comment by samjar** [comment]
I was afraid something like that would be too difficult to code, and thought perhaps hackers could bypass something like that. After all, they're flying and stuff already lol

In my case, no matter what they try, they can't get past the fact that the tiles that are dark. Your idea is really cool, though, and makes it more exciting considering you have to carry torches with you. Will it be hard to code?

I forgot to mention in the original post, but I didn't plan for the entire dungeon to be _completely_ dark. In several rooms, there will be crystal models that are visible in the dark, and illuminates a faint light (just gonna draw a lighter-colored circle of tiles on the floor, or walls, close by it). That way, while most of the holes, traps and obstacles, are hidden in the dark, at least players can navigate through the room _some_. I'm not a complete sadistic lunatic, you know ;D
