### ISSUE TITLE
test how the world looks like when the world is smaller (x0.5 scale)

### ISSUE THREAD

**Issue by nickjanssen** [ironbane/IronbaneServerLegacy#190]
`not that bad that they are midgets but why would midgets built houses 20x bigger than them with stairs they need to climb up`

as suggested by @Meanapple because some world objects are super huge and doesn't make much sense. Although currently it doesn't bother me that much

**Comment by bsparks** [comment]
it does bother me that the innkeep can't see over the bar. some barrels and boxes are too big. some things however don't feel too big, so I'm not sure a flat scale will work

**Comment by ghost** [comment]
This doesn't seem to have progressed at all, so I'm gonna mark this is closed unless we really think the current scale hampers player's experience with the game.

Personally, I've yet to hear a complaint or comment on how big things are. :)
