### ISSUE TITLE
Healing doesnt work

### ISSUE THREAD

**Issue by TheRestIsATest** [ironbane/IronbaneServerLegacy#205]
Healing wands hurt enemys but do not heal allies

**Comment by ingmargoudt** [comment]
Please test in the latest build on the dev-server.
fix in commit 2ce72c3

**Comment by samjar** [comment]
The healing still doesn't work. It damages enemies and doesn't heal allies. I have double-checked the database to see if the wands have negative values assigned to them, and they do.

**Comment by ingmargoudt** [comment]
tested and confirmed to be working!
