### ISSUE TITLE
gruntfile: auto deploy .min when isProduction is true

### ISSUE THREAD

**Issue by ingmargoudt** [ironbane/IronbaneServerLegacy#207]
Currently on production ironbane0.4.0.js is deployed, giving players full insight on the codebase . On production ironbane0.4.0.min.js should be deployed. Adapt the gruntfile in such a way that the appversion variable is set based on the value of isProduction (config-file)

**Comment by bsparks** [comment]
prolly some variable like @@useMinfied (that can be based on production or any other condition)

**Comment by ingmargoudt** [comment]
this was fixed by Nikke
