### ISSUE TITLE
update node.js to 10.x

### ISSUE THREAD

**Issue by nickjanssen** [ironbane/IronbaneServerLegacy#208]

**Comment by ghost** [comment]
Has this been done yet?

**Comment by lschans** [comment]
Yes is has, auto updates to latest version now with yum

On Mon, Dec 9, 2013 at 2:18 AM, DatapawWolf notifications@github.comwrote:

> Has this been done yet?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ironbane/IronbaneServer/issues/208#issuecomment-30099953
> .

## 

---

Lars van der Schans

**Comment by ghost** [comment]
Hooray! If you see any other technical issues that have been completed then please close those as well. I'm trying to close down as many older issues as I can.

**Comment by lschans** [comment]
You are the best in closing issues. Dont want to be in your way man. xD

On Mon, Dec 9, 2013 at 7:01 PM, Kevin notifications@github.com wrote:

> Hooray! If you see any other technical issues that have been completed
> then please close those as well. I'm trying to close down as many older
> issues as I can.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ironbane/IronbaneServer/issues/208#issuecomment-30155586
> .

## 

---

Lars van der Schans
