### ISSUE TITLE
add screenshot mode parameter in URL

### ISSUE THREAD

**Issue by nickjanssen** [ironbane/IronbaneServerLegacy#211]

**Comment by ingmargoudt** [comment]
what do you mean with this issue?

**Comment by nickjanssen** [comment]
Adding a parameter to the URL like &screenshotmode=1 will hide the HUD and allow you to make nice screenshots

**Comment by bsparks** [comment]
why the url? just call hudHandler.hide() (or similar) from the console instead? and/or add a button?

**Comment by nickjanssen** [comment]
I figured that not everyone would be able to use the console ;) but perhaps you are right.

On 06.11.2013, at 18:29, "Ben Sparks" <notifications@github.com<mailto:notifications@github.com>> wrote:

why the url? just call hudHandler.hide() (or similar) from the console instead? and/or add a button?

##

**Comment by ghost** [comment]
Button would be nice. Makes it easy for any user to take screenshots. We want as many regular players to post screenshots around the web as possible. :)

**Comment by lschans** [comment]
Yeah and maybe even a double screenshot mode, with and without chatbox
visible.

On Fri, Nov 8, 2013 at 8:58 PM, DatapawWolf notifications@github.comwrote:

> Button would be nice. Makes it easy for any user to take screenshots. We
> want as many regular players to post screenshots around the web as
> possible. :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ironbane/IronbaneServer/issues/211#issuecomment-28093063
> .

## 

---

Lars van der Schans

**Comment by ghost** [comment]
What about: http://experiments.hertzen.com/jsfeedback/
Would this be possible to allow client-sided screenies?

**Comment by ingmargoudt** [comment]
screenshot mode added in 93f1442
toggle by pressing 'u'

**Comment by bsparks** [comment]
I think you need to hide the FPS, editor, and debug stuff. I imagine shots will be taken as an editor quite often.

**Comment by ingmargoudt** [comment]
Will add that! :)

Verstuurd vanaf mijn iPhone

**Comment by ghost** [comment]
Now we just need the FPS box to be hidden. I believe everything else is working, though. Can you close the issue once it is completed, Ingmar?

**Comment by ingmargoudt** [comment]
FPS box is now shown as well
