### ISSUE TITLE
Temporarily shrink the world

### ISSUE THREAD

**Issue by samjar** [ironbane/IronbaneServerLegacy#223]
The world is too large, vast and empty at the moment. Me and Nick discussed it and we agreed that we should probably start smaller, and fill out the stuff that we already got before we start adding more. So now there will be a much smaller world, but we'll add the other locations again as we expand it. This is also so we can add a castle and Ironbane himself to the game, so players actually have a goal at this point. 

**World**
- [x] Temporarily remove parts of the world where people won't be going.
- [x] Make an outline of the new world.
- [x] Add Mountains behind the castle's new location.
- [x] Fix the river.
- [ ] Add castle exterior, e.g. walls, towers.

_Extra_
- [ ] Do the tedious work of removing all the extra NPC's, models, and stuff that will now be floating in nowhere land, once we remove the terrain it sits on. Ugh.

**Castle Interior**
- [x] Draw blueprints of a much smaller castle interior.
- [ ] Create model of the castle interior.

**Comment by nickjanssen** [comment]
I can remove the remaining floating NPC's and models!
