### ISSUE TITLE
map glitches for 0.4.1

### ISSUE THREAD

**Issue by nickjanssen** [ironbane/IronbaneServerLegacy#227]
a small triangle is floating in the air?
![image](https://f.cloud.github.com/assets/2780160/1364519/8e6b9a5e-3840-11e3-8414-7fbc41f5ff02.png)

**Comment by samjar** [comment]
Can you give me the coords to this triangle? By the way, I fixed everything else.

**Comment by nickjanssen** [comment]
Its next to the castle, right after crossing the bridge
