### ISSUE TITLE
Website Issue - Quoting in a Certain Fashion Kills Thread Formatting

### ISSUE THREAD

**Issue by ghost** [ironbane/IronbaneServerLegacy#231]
So I was messing around with quotations, and lo and behold, I came upon a very bizarre glitch as seen here: http://oi40.tinypic.com/29pciyp.jpg

The exact post content was this:

[quote=laxattack1226][quote=DatapawWolf][quote=laxattack1226][quote=DatapawWolf][quote=laxattack1226]quote=DatapawWolf][quote=laxattack1226]If you tell me where john is, THEN that MIGHT help...[/quote]Never passed the sign about "Leslie's Place" and "Ravenwood" and the slime forest? There's a little house with some people. :)
[/quote]I've only seen leslie's. Do I have to go passed him or have I missed him ?[/quote]Apparently the vendor guy is right there in the house.[/quote]The vendor is Leslie, but WHERE IS JOHN[/quote]Somewhere for sure! ;D[/quote]GRRR... Pweez tell me?[/quote]

And can be seen here: http://www.ironbane.com/forum.php?action=topic&topic=555

**Comment by nickjanssen** [comment]
Yep...it's because the quote start and end tags don't check if the quote is actually closed. Just super bad (and old) coding of mine. Will be fixed in the new forum update!

**Comment by ingmargoudt** [comment]
This is part of the legacy website, and will not be fixed. The new forums will give support for quoting.
