### ISSUE TITLE
commands like /who crashing the sever

### ISSUE THREAD

**Issue by nickjanssen** [ironbane/IronbaneServerLegacy#244]
They crash the server, due to a bug in the sockets  list.

Some sockets for some reason do not have a unit attached, it is null. So we either need to find out why some sockets's unit variable is null or do a check when looping over the sockets

https://github.com/ironbane/IronbaneServer/blob/master/src/server/game/chat/chatHandler.js#L258

probably related to #92

**Comment by bsparks** [comment]
seems like it's fixed! re-open if it still happens (please)
