### ISSUE TITLE
Cannot type @ in chat

### ISSUE THREAD

**Issue by eric-ycw** [ironbane/IronbaneServerLegacy#247]
1.
If you type @player (msg), you can't send the msg.

2.
If you type @(your own character name), you will have this msg. [player name] <player name>

P.S. in the first point, the player shouldn't be yourself

**Comment by bsparks** [comment]
I think that it should still be sending the message with @player , just there is not any feedback (there should be). So it looks like it's going nowhere.

**Comment by lschans** [comment]
Yes we know about this, everything that has to do with rooms and pm's is
disabled for now. 0.4.2 is the next chance

On Wed, Oct 23, 2013 at 3:53 PM, Ben Sparks notifications@github.comwrote:

> I think that it should still be sending the message with @playerhttps://github.com/player, just there is not any feedback (there should be). So it looks like it's
> going nowhere.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ironbane/IronbaneServer/issues/247#issuecomment-26906344
> .

## 

---

Lars van der Schans

**Comment by bsparks** [comment]
I think this is fixed.
