### ISSUE TITLE
structure angular forum into a modular system

### ISSUE THREAD

**Issue by nickjanssen** [ironbane/IronbaneServerLegacy#248]
Currently in the forum all angular files are sorted by their file type. (a views folder for templates, one for directives, one for controllers, etc) Angular now recommends to put files together in a modular fashion as this is a lot easier to work with. We are now doing this at our work too and it's really a lot better as controllers and their views and other associated files tend to grow at the same pace. This is why it makes more sense to put them in one folder.

Angular is now doing it too: https://github.com/angular-app/angular-app/tree/master/client/src/app

**Comment by bsparks** [comment]
yeah I started doing it at work recently too, will work on it

**Comment by ingmargoudt** [comment]
fixed in  a3aca06926833f5d984ed7ff06f429ca8f669c39
