### ISSUE TITLE
Tell us which update we're on

### ISSUE THREAD

**Issue by ChaiTeaNunes** [ironbane/IronbaneServerLegacy#250]
So, I was playing, and I was about to die, when I realized there was no health regen. I was like "oh sh*t" and then I died. I didn't know that it was v0.4.1

**Comment by bsparks** [comment]
the version's on the main screen

**Comment by ChaiTeaNunes** [comment]
It still says 0.4.1

**Comment by bsparks** [comment]
you mean on dev? for the next version someone just has to update the package.json file, and someone usually does before it goes live.

**Comment by ChaiTeaNunes** [comment]
I mean on normal... I'm not a dev. Well, can someone update that? I might be able to, it depends.
