### ISSUE TITLE
Forum Moderation Tools & Post Suggestions

### ISSUE THREAD

**Issue by ghost** [ironbane/IronbaneServerLegacy#254]
Here are some handy moderation tools as well as suggestions for fixes that would be nice to have for making moderation simpler:
- [ ] Deleting individual posts. A little "Delete" button placed next to the current quote button that prompts for deletion. Only visible to moderator priviledges.
- [ ] Lock thread feature. This would be extremely useful for preventing spam.
- [ ] Edit button. Editing is already a function of mods and above, but there are no buttons for it. A little "Edit" button should be placed just like the proposed delete button.
- [ ] Merge threads. This just involves marking two threads and then taking the posts of one and putting them in the most recent thread. The first post of the older thread should have an option to be included since sometimes the reason to merge threads is that they are nearly identical.
- [ ] Merge posts. Self-explanatory, would be a useful feature to have for those that feel the need to post multiple times in a row.
- [ ] Move post(s) or thread(s). Sometimes posts and or/threads wind up in the wrong place and need to be moved.
- [ ] Global stickies. Sometimes local sub-forum only stickies aren't enough. Global stickies are useful for forum rules, permanent announcements, & etc.
- [ ] A definite distinction between the "Bugs" and "Editor Suggestions & Bugs" sub-forums since both are crowded with IBN bugs.

Post suggestions:
- [ ] Fixes for quotations
- [ ] Add spoiler tags
- [ ] YouTube video tags (ones that embed YouTube video frames) - not needed but would be nice to have
- [ ] Delete tags (http://www.w3schools.com/tags/tag_del.asp)

This is it for now, I will add more suggestions if I can think of any. More ideas are appreciated!

**Comment by eric-ycw** [comment]
Edit? How? (n00b)

**Comment by ghost** [comment]
Yep. Editing others posts is currently a manipulation of the post number ID and using the editing URL.

**Comment by eric-ycw** [comment]
Lol I didn't know that at all o.O

**Comment by ghost** [comment]
I usually just pick these things up because I'm more oriented towards a hacker's mindset. So if I can easily get around restrictions I'll do just that. ;)

**Comment by ingmargoudt** [comment]
Datapaw, can  you merge this with issue 195?
