### ISSUE TITLE
Update ironbane run commands

### ISSUE THREAD

**Issue by jacob2512** [ironbane/IronbaneServerLegacy#258]
I believe
      <code>ironbane init</code>
and 
      <code>ironbane start</code>
does not work correctly in Linux.

Instead i was able to run it with 
      <code>node ironbane.js init</code>
and 
      <code>node ironbane.js start</code>

Please update this in the README if it is useful.

**Comment by bsparks** [comment]
they do work, you have to chmod 755 the file to make it executable however. that is what should be added to the readme

**Comment by jacob2512** [comment]
Tried changing ironbane.js to 755 access.
<code>ironbane init  </code>
still does not work, but
<code>./ironbane.js init </code>
works.
I see now that the README has been changed to
what was suggested originally.

**Comment by bsparks** [comment]
hmmm gotcha, I suppose you'd have to create a sym link called "ironbane" to the executable... maybe, or maybe @lschans can tag in with some 'nix magic

**Comment by lschans** [comment]
Silly linux ;)

It's cleaner to just make ironbane.js executable.

chmod +x ironbane.js

This only sets the executable flag to the file.

if you dont want to executable script all over your system you can also
call it with node in front of it.

node ironbane.js start

I will update the README for this this week

On Sun, Oct 27, 2013 at 5:52 AM, Ben Sparks notifications@github.comwrote:

> hmmm gotcha, I suppose you'd have to create a sym link called "ironbane"
> to the executable, that'd prolly get it finished (silly linux)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ironbane/IronbaneServer/issues/258#issuecomment-27162944
> .

## 

---

Lars van der Schans
