### ISSUE TITLE
Global chat and player names

### ISSUE THREAD

**Issue by lschans** [ironbane/IronbaneServerLegacy#259]
In the chat, the global chat function doesn't work anymore. Chatting without a room or user should be global.

Also unit.name should work case insensitive for chatting.

So @Nikke, @NIKKE, @nikke should all work.

**Comment by bsparks** [comment]
commit b6e1d66c4b4f3d9e95e602baf76653b7407c7828 fixes this (not sure why auto comment didnt work)
