### ISSUE TITLE
Disable "Submit" Button After Click

### ISSUE THREAD

**Issue by ghost** [ironbane/IronbaneServerLegacy#262]
This is a really simple fix I'd like to see for multiple posting. The main reason for posting multiple times is clicking the submit button twice on accident.

So, disable the button after the first click. This should help reduce clutter in the forum, and prevent anyone from abusing the system and posting a hundred times in a row.

**Comment by ingmargoudt** [comment]
This is already resolved in the new forums software. Try it out on the dev server

Verstuurd vanaf mijn iPhone

**Comment by ghost** [comment]
Oh ok.

Where is the dev server? Technically I applied as a moderator, so I hadn't really thought about checking out all the dev stuff. Is there a link?

**Comment by bsparks** [comment]
try not to post links to it, send PM messages. we don't want it getting hit by the public

**Comment by ingmargoudt** [comment]
Please look at issue 195 , and on the development environment. Ask the location by PM or by Skype

**Comment by ingmargoudt** [comment]
Resolved in new forum software
