### ISSUE TITLE
Doesn't display right damage on weapons

### ISSUE THREAD

**Issue by samjar** [ironbane/IronbaneServerLegacy#276]
After 4 hearts, it doesn't display any higher. For example, a weapon that deals 10 hearts still only displays 4 hearts.

**Comment by bsparks** [comment]
![screenshot 2013-11-01 13 00 03](https://f.cloud.github.com/assets/384189/1456634/5c79e6ae-4330-11e3-8afb-a910c99ce40e.png)

im not seeing that issue, you sure?

**Comment by samjar** [comment]
Hmm, it seems to work now. Weird. I love it when bugs fix themselves, don't you? :D

Case closed.
