### ISSUE TITLE
Character Animations are no longer playing

### ISSUE THREAD

**Issue by bsparks** [ironbane/IronbaneServerLegacy#286]
walking animations for player and npc (Fighter)

**Comment by ingmargoudt** [comment]
yes, I moved all loose timers to the timers object in unit.js on the client, I think there the problem resides because the walkSpriteTimer does not appear to be updated correctly.

**Comment by ingmargoudt** [comment]
Good job fixing that! :-)

Verstuurd vanaf mijn iPhone
