### ISSUE TITLE
Banks

### ISSUE THREAD

**Issue by TheRestIsATest** [ironbane/IronbaneServerLegacy#287]
People are desperately asking for banks or a larger inventory. When are we going to work on it?

**Comment by lschans** [comment]
Dont know, I do know that Kevin had a good idea for this.

On Tue, Nov 5, 2013 at 1:52 PM, Meanapple notifications@github.com wrote:

> People are desperately asking for banks or a larger inventory. When are we
> going to work on it?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ironbane/IronbaneServer/issues/287
> .

## 

---

Lars van der Schans

**Comment by bsparks** [comment]
duplicate of issue #37
