### ISSUE TITLE
DEPRECATED MySQL Extension

### ISSUE THREAD

**Issue by Scottss** [ironbane/IronbaneServerLegacy#29]
MySQL Extension code should be updated to the newer MySQLI Extension
![2360c8a793a6fd80468685cf1115d664](https://f.cloud.github.com/assets/4674727/672144/163c1dd0-d871-11e2-9636-6934457dfe08.png)

**Comment by jordan-schnur** [comment]
We would have change every SQL statement. This should be done, but not as this time.

**Comment by ingmargoudt** [comment]
The php mysql extension is indeed deprecated. 
This will be fixed in the webapi branch, since that branch does not use php.
In case you want to continue on the php branch, you could also use PDO statements.
