### ISSUE TITLE
Undead Crypt, Pumpkin Island, and Ghost House

### ISSUE THREAD

**Issue by ChaiTeaNunes** [ironbane/IronbaneServerLegacy#293]
I heard there was going to be these, so I wanted to add little rewards.

Bone Spear: http://makepixelart.com/peoplepods/files/images/992224.original.png
Pumpkin Spear: http://makepixelart.com/peoplepods/files/images/992229.original.png
Ghost Spear (Transparent): http://piq.codeus.net/static/media/userpics/piq_144814_400x400.png

For the 16x16 version of the Ghost Spear, use this: 
http://piq.codeus.net/static/media/userpics/piq_144814_16x16.png

**Comment by ghost** [comment]
Not that we won't be needing graphics for these areas, but I don't think we are going to be adding them in any time soon. So for now I'm gonna close this. Thanks!
