### ISSUE TITLE
Chat doesn't show up all the time

### ISSUE THREAD

**Issue by bsparks** [ironbane/IronbaneServerLegacy#300]
seems to be related to whether or not dev tool is open??

**Comment by bsparks** [comment]
thought it was fixed, not showing up in firefox... however I think that #297 may only occur when the chat is present

**Comment by bsparks** [comment]
sigh... .still doesn't work in FF

**Comment by nickjanssen** [comment]
Doesn't show at all! Even on chrome, incognito mode!
