### ISSUE TITLE
Selling Any Item Gives 10 Gold

### ISSUE THREAD

**Issue by ghost** [ironbane/IronbaneServerLegacy#307]
This is occurring for sure on the public server.

Take any item.
Sell to vendor.
It will say "I'd offer X..." on the okay screen and display the correct value, half of the item value.
When okay is clicked, you are given 10 gold.

This happens for items both over and under 10 gold in value. Can also be done to turn a 2 gold stack by selling it to the vendor, who will offer 1 gold and gives you ten.

**Comment by bsparks** [comment]
fixed
