### ISSUE TITLE
The Area Behind Arrow Projectiles is Black

### ISSUE THREAD

**Issue by ghost** [ironbane/IronbaneServerLegacy#308]
> > ------>
> > Take this as the arrow. Looking lengthwise we see no issue.
> > x
> > Looking from the tip toward the back has no issue.

However, there is a black square that appears only when viewing the back. From the front side, it does not appear.

Screenshots pending.

**Comment by ingmargoudt** [comment]
fixed in 401ad37

**Comment by bsparks** [comment]
looks fixed to me!
