### ISSUE TITLE
Navigation mesh pathfinding

### ISSUE THREAD

**Issue by nickjanssen** [ironbane/IronbaneServerLegacy#31]
We currently use a waypoint-based approach for pathfinding, which is okay. But it is not the greatest. Read this for more info: http://www.ai-blog.net/archives/000152.html

Monsters are currently quite dumb in their navigation and sometimes walk through walls and stuff. Not to mention that we all need to place waypoints everywhere. And if done correctly nav meshes are more performant.

It's probably super hard to do though :P as there is no JS library yet for 3D navigation mesh pathfinding. A unique chance for us maybe!

**Comment by bsparks** [comment]
sounds fun! :dancers:
