### ISSUE TITLE
Change zeppelin path over farm

### ISSUE THREAD

**Issue by lschans** [ironbane/IronbaneServerLegacy#324]
Change zeppelin path over farm? ( Kevin's idea? )

**Comment by ghost** [comment]
Yes. For other's info, this will to make a simple parkour area using stone up the tiny mountain. By moving the zeppelin path this keep other players from simply jumping on the rock.

Reward suggestions (or if I just shouldn't do this lol) would be appreciated. I'm thinking a batch of fruit and maybe a weapon like a pitchfork or such.
