### ISSUE TITLE
Money dup bug

### ISSUE THREAD

**Issue by lschans** [ironbane/IronbaneServerLegacy#325]
Money duplication bug, we all know this one.

If the bug is solved? Craft a query that sets all money bags to 100 Gold ( to balance the game )

**Comment by ingmargoudt** [comment]
UPDATE ib_items SET VALUE = 100 WHERE template = 78;
UPDATE ib_items SET VALUE = 100 WHERE template = 89;
UPDATE ib_items SET VALUE = 100 WHERE template = 90;
