### ISSUE TITLE
Write query to unbind rare items 

### ISSUE THREAD

**Issue by lschans** [ironbane/IronbaneServerLegacy#326]
Write query to unbind all dragon armor items and teddybears ( to balance the game ) 

49 Dragon's Head, 69 Dragon Boots, 86 Teddybear, 88 Sapphire Armor, 138 Ironbanes Shard, 139 Ironbanes Blade, 140 Ironbanes Bow, 141 Ironbanes Cleaver

**Comment by ingmargoudt** [comment]
DELETE FROM ib_items WHERE template = 49;
DELETE FROM ib_items WHERE template = 69;
DELETE FROM ib_items WHERE template = 86;
DELETE FROM ib_items WHERE template = 88;
DELETE FROM ib_items WHERE template = 138;
DELETE FROM ib_items WHERE template = 139;
DELETE FROM ib_items WHERE template = 140;
DELETE FROM ib_items WHERE template = 141;
