### ISSUE TITLE
Lootbag inventories are on a pile instead of aligned and spread

### ISSUE THREAD

**Issue by lschans** [ironbane/IronbaneServerLegacy#327]
Lootbag inventories are on a pile instead of aligned and spread

**Comment by bsparks** [comment]
they are not, there are only slots showing for items in the bag, no extra slots

**Comment by lschans** [comment]
Okay, but this makes it hard to trade items for players. you can all swap
items and use a bag for this. Now you need to place lots of bags.
But if its not a bug, we see how players think of it.

And close the issue

On Mon, Nov 18, 2013 at 4:03 PM, Ben Sparks notifications@github.comwrote:

> they are not, there are only slots showing for items in the bag, no extra
> slots
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ironbane/IronbaneServer/issues/327#issuecomment-28704512
> .

## 

---

Lars van der Schans
