### ISSUE TITLE
More healing equipment

### ISSUE THREAD

**Issue by lschans** [ironbane/IronbaneServerLegacy#328]
We should have more healing equipment for healers ingame.
Maye some outfits, wands, etc

**Comment by ghost** [comment]
When the church is decked out, maybe we could make that the designated area to farm healing equipment. Since it would be powerful support - the ability to heal - we could make it somewhat rare. Plus, having to travel for it would deter anyone from simply picking up a wand somewhere and going heal-happy, getting other players killed because "I r not teh neob."

I'm exaggerating, but still, it makes more sense in the church than anywhere else. ;)

**Comment by bsparks** [comment]
I think there needs to be a 1 heart heal "starter" staff available in the town church. Along with some basic priest robes. so that ppl can chose to "roll a healer".

**Comment by lschans** [comment]
If we can combine this with the onEquip issue
https://github.com/ironbane/IronbaneServer/issues/330
we can even make this a healer/priest class. This would be a good 'class'
test

On Tue, Nov 19, 2013 at 1:03 AM, Ben Sparks notifications@github.comwrote:

> I think there needs to be a 1 heart heal "starter" staff available in the
> town church. Along with some basic priest robes. so that ppl can chose to
> "roll a healer".
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ironbane/IronbaneServer/issues/328#issuecomment-28753580
> .

## 

---

Lars van der Schans

**Comment by ghost** [comment]
Rethinking and stuffs, I think I get it. What if you had a layout where other players could "scan" another player's equipment to determine what role their equipment would best play? Like, for example:
Player A has Healer Robe and Claymore equipped
Player B has Healer Robe and Healer Staff equipped

Player A would have one point in Healer and one point in Warrior.
Player B would have two points in Healer and none in Warrior.

When they are both scanned by, let's say, a designated team scout, they could pick the player that best fits their needs. If they only need a secondary healing support, then they may choose the one with both Warrior and Healer points.

:D

And when I mentioned the church, I originally meant that one up on the hill that was in the previous map iteration. Back when was a wee player, I assumed it was going to be overrun with skellies and necromancers (hence my story on the forum including a bit about slaying a necromancer in the church).

But I guess one in the city would still work. :)

**Comment by bsparks** [comment]
I think it'd be easier to just let the player say "hey, I'm rolling a Priest today"

**Comment by ghost** [comment]
Certainly it would be easier. I'm just saying that scouting other players for builds useful to a party of players would be a neat feature.

**Comment by bsparks** [comment]
made a priest in town next to the shrine that sells healing stuff, other than having a church I think this is a good start
