### ISSUE TITLE
Christmas Wishlist

### ISSUE THREAD

**Issue by bsparks** [ironbane/IronbaneServerLegacy#342]
Please feel free to add / modify this list; Also would be good to have at least one quest and some special items. Doesn't have to be all christmas, just winter theme is good. Maybe do some GoT references, "winter is coming". :)
- [x] pine tree (snow covered a big one for /stuck and small ones for the village)
- [x] mistletoe
- [x] socks
- [x] mistletoe
- [x] santa statue
- [x] igloo
- [ ] Huge xmas hat on the runestone
- [x] xmas balls
- [x] present boxes
- [x] replace grass with snow (world zone)
- [x] snow precipitation (3d particles like clouds)
- [ ] wreath
- [x] snowman sprite
- [x] ice goblin
- [x] snowball projectile
- [x] snow staff (weapon)
- [x] hot cocoa
- [x] glass of milk
- [x] cookies
- [x] candy cane

**Comment by lschans** [comment]
How about Santa and reindeer instead of zeppelins

**Comment by ghost** [comment]
Some games make special present items that are equippable by the player. Basically they can buy these "boxes" which can be used as armor, weapons, and etc.
On Christmas, they are automatically replaced with special Christmas-themed items. :) So the whole idea is waiting for Christmas to get your special items.

For the pine tree. Maybe a gigantic one on top of the plateau in Ravenwood. :3

Could we also do a special one-time event? Maybe something like a Christmas invasion? Attack of the snow men? XD

**Comment by jesse-stojan** [comment]
I like Lars idea about the Slay with Reindeer

**Comment by ghost** [comment]
Two more models left! Are we going for the last two requests or just close it down?

**Comment by lschans** [comment]
I'd say that if someone that is very handy with blender and also makes
great santa's.. ( Not pointing at anyone )
Has time, we should finish the list.

On Sun, Dec 8, 2013 at 10:42 PM, DatapawWolf notifications@github.comwrote:

> Two more models left! Are we going for the last two requests or just close
> it down?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ironbane/IronbaneServer/issues/342#issuecomment-30093697
> .

## 

---

Lars van der Schans

**Comment by ghost** [comment]
Yeah, I mean if anyone _coughjessecoughcough_ has some time, those last two models would be a nice addition. Maybe we could hang the wreath from the mountain where the bank is at. :D

**Comment by lschans** [comment]
Yeah especially if someone ( dunno who ) who can, would make it a special
ornament for the bank entrance/inn entrance..

On Sun, Dec 8, 2013 at 10:51 PM, DatapawWolf notifications@github.comwrote:

> Yeah, I mean if anyone _coughjessecoughcough_ has some time, those last
> two models would be a nice addition. Maybe we could hang the wreath from
> the mountain where the bank is at. :D
> 
> ---
> 
> From: Lars van der Schans notifications@github.com
> To: ironbane/IronbaneServer IronbaneServer@noreply.github.com
> Cc: DatapawWolf arthasthelichking@sbcglobal.net
> Sent: Sunday, December 8, 2013 3:45 PM
> Subject: Re: [IronbaneServer] Christmas Wishlist (#342)
> 
> I'd say that if someone that is very handy with blender and also makes
> great santa's.. ( Not pointing at anyone )
> Has time, we should finish the list.
> 
> On Sun, Dec 8, 2013 at 10:42 PM, DatapawWolf notifications@github.comwrote:
> 
> > Two more models left! Are we going for the last two requests or just
> > close
> > it down?
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/ironbane/IronbaneServer/issues/342#issuecomment-30093697>
> > 
> > .
> 
> ## 
> 
> ---
> 
> Lars van der Schans
> —
> Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ironbane/IronbaneServer/issues/342#issuecomment-30093898
> .

## 

---

Lars van der Schans

**Comment by ghost** [comment]
Also.. "pine tree (snow covered a big one for /stuck.."
It's not done yet! We need a GIANT CHRISTMAS TREE!!

**Comment by ghost** [comment]
Well since no one picked it up, I'm gonna close this. Thankfully most of this was finished. :)
