### ISSUE TITLE
Loading javascripts after initial load

### ISSUE THREAD

**Issue by kojagiri1934** [ironbane/IronbaneServerLegacy#361]
var elements = [];

function tryLoader() {
    if (elements.length > 0) {
    var a = elements.pop();
    //update progress bar or some sort here

```
exty = a.substring(a.lastIndexOf(".") + 1).toLowerCase();
if (exty == "js" || exty == "aspx") {
// load the relevant JS and continue with the next one
$.getScript(a, tryLoader);
}
} else { 
doneLoader();
}
```

}

function doneLoader() 
{
//... proceed with the rest
}

**Comment by kojagiri1934** [comment]
Initially only jquery.js and this script would need to be loaded - all else can load dynamically. 

Raised in response to Line 13 that says ""

**Comment by ingmargoudt** [comment]
We are planning to migrate the game client code to AngularJS, which handles the loading of dependencies.
Besides that, all of the javascripts are concatenated in 1 big file

**Comment by kojagiri1934** [comment]
Why add a fresh plugin when this simple script would suffice? Plus combining all JS in one big file is very load-unfriendly and can be super-hard to maintain. Extra work for us and the browser.

**Comment by bsparks** [comment]
im not really sure what you're suggesting with this issue.

**Comment by kojagiri1934** [comment]
@bsparks "Here is the solution to the automate libs/late loading/dynamic js calling aspect that is currently not a part of IB". What I've put up is the solution, targeted at whoever's working on that/angularjs. If nobody is, that's cool - we can address this later.

**Comment by ingmargoudt** [comment]
Sorry, but we are still missing what you are trying to suggest here. The JS is concatenated during a grunt build, and has nothing to do with code maintain ability. AngularJS , as soon as we transfer the game client code to that, will handle the dependency injections

**Comment by kojagiri1934** [comment]
@ingmargoudt yes the dependency handler in Angluar would take care of this - I'm closing the issue.
