### ISSUE TITLE
make item loading more robust

### ISSUE THREAD

**Issue by ingmargoudt** [ironbane/IronbaneServerLegacy#373]
Whenever a character references a missing item template id, dont break the game.
Patch 0.4.6 removed item template id 88, which still had instances which where not removed. Every character that had an item with template id 88 in his inventory or bank, could not log in.

**Comment by ingmargoudt** [comment]
fixed in 2864551

**Comment by ghost** [comment]
If this is fixed then I will close it for now. If for some reason it breaks again then we can reopen it.
