### ISSUE TITLE
More Leggings Sprites

### ISSUE THREAD

**Issue by eric-ycw** [ironbane/IronbaneServerLegacy#378]
There are too little leggings in game currently.

**Comment by ghost** [comment]
I thought @Meanapple said he added a whole bunch of new items? If so, we don't really need this issue for now. It's just that players will have to wait until we push the next release.

**Comment by TheRestIsATest** [comment]
actually Ben did it.. I think some day we need to remove every item and redo everything ground up

**Comment by ghost** [comment]
I think better yet, just list 'em all out line by line and sort 'em.
Just as long as we aren't wiping anyone's stuffs.

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by eric-ycw** [comment]
As I saw pretty many new leggings around, I'll close this issue.
