### ISSUE TITLE
[Chore] Asset Organization

### ISSUE THREAD

**Issue by bsparks** [ironbane/IronbaneServerLegacy#41]
need to find a better way to store and keep track of all the sprites, meshes, etc so that they don't get accidentally edited/duplicated/deleted and so that we can quickly view a catalog of them to know what we have.

perhaps the assets should be in a separate repo, other ideas?

**Comment by nickjanssen** [comment]
Agreed...we will need a private repo for this. We can use BitBucket for now.

I read that it is possible using sub-modules too, but I fear that will get super complicated

**Comment by bsparks** [comment]
does it have to be private? are the art assets closed source? we can still allow core ppl to modify directly and require others to do PR right?
