### ISSUE TITLE
Book bug

### ISSUE THREAD

**Issue by eric-ycw** [ironbane/IronbaneServerLegacy#431]
http://www.ironbane.com/forum.php?action=topic&topic=1461

A glitch where the text ignores the boundaries of the book, and the text continues downward the screen.

**Comment by Guigo91** [comment]
Issue comes from css and from text book content.

IronbaneServer / src / client / game / css / ironbane.less 

#book {
  display:none;
  position:absolute;
  width:460px;
  height:420px;
  background-image:url(../media/images/misc/book.png);
}

.bookPage {
  width:160px;    should be 230px (460 / 2)
  height:320px;
  float:left;
}

From IronbaneServer / install / 1_base.sql, in book table create statement, there are too many <div><br></br>

INSERT INTO `ib_books` (`id`, `title`, `text`)
VALUES
       ...
        (2,'Fibula Spear','<div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div>The great and powerful Fibula Spear. ...

I guess  (2,'Fibula Spear','<div><br></div><div><br></div><div><br></div>The great and powerful Fibula Spear...
is ok.

**Comment by eric-ycw** [comment]
Hm, @Guigo91 Maybe you can make a commit?

**Comment by Guigo91** [comment]
I run Ironbane on localhost. I commit on my develop branch.
Could I push on develop branch of Ironbane git directly ? Actually, I am not really familiar with git.

**Comment by eric-ycw** [comment]
Me too, you'll have to ask the other devs about that.

**Comment by eric-ycw** [comment]
Fixed.
