### ISSUE TITLE
Twitter account

### ISSUE THREAD

**Issue by nickjanssen** [ironbane/IronbaneServerLegacy#434]
I am not very good at twitter. Is there anyone who wants to post messages from time to time on it? @DatapawWolf still interested?

**Comment by ghost** [comment]
I'm still interested, yes. Just trying to get back into the swing of things. :) I did have some recent ideas about what to post, so perhaps keep an eye on the Twitter acc.

**Comment by bsparks** [comment]
I suggest also participating in #screenshotsaturday and other gamedev hashtags

**Comment by ghost** [comment]
Good point. I don't know all the hashtags, but I've noticed #GameDev for sure, which seems to be popular. If you have any good ones, post 'em here.

**Comment by nickjanssen** [comment]
@DatapawWolf is doing an outstanding job!

**Comment by ghost** [comment]
Thanks, @nickjanssen! :)

**Comment by ingmargoudt** [comment]
closing this "issue" , twitter account is being maintained
