### ISSUE TITLE
Guest's name color in chat when logging in isn't orange

### ISSUE THREAD

**Issue by eric-ycw** [ironbane/IronbaneServerLegacy#442]
When you have the message "Guest has joined the game!" The guest name is blue, not orange.

**Comment by Guigo91** [comment]
In IronbaneServer / Engine / SocketHandler.js, when chatMessahe is emited, rank is not given in user object : 

```
        req.io.emit('chatMessage', {
            type: 'welcome',
            user: {
                id: unit.id,
                name: unit.name,
```

// ===========  ADD
                    rank: unit.isGuest ? 'guest' : (unit.editor ? 'gm' : 'user')
// =========== 
                },
                online: socketHandler.onlinePlayers
            });

Not tested yet

**Comment by msouth** [comment]
Thanks @Guigo91 . I think I'm going to take a shot a eliminating the need for repeating that rank computation everywhere.

We'll see how it goes :).

**Comment by ingmargoudt** [comment]
The guest name is now listed in orange as of Guigo91's PR
