### ISSUE TITLE
[Spawn] Add NPC that hands out free dull swords 

### ISSUE THREAD

**Issue by nickjanssen** [ironbane/IronbaneServerLegacy#45]
See https://github.com/ironbane/IronbaneServer/commit/dd92f4044e25d960071470f0aa4989b1db85c97c#L1L392

**Comment by nickjanssen** [comment]
Working, but people tend to not see this NPC when they respawn and just go on without a sword. How about giving a sword automatically instead once you finished the tutorial?

**Comment by bsparks** [comment]
well how are they fighting anything? I suppose it doesn't matter too much whether we give them a sword automatically for now. maybe take it away again once there are banks and the town is populated

**Comment by bsparks** [comment]
seems like this is done, guy lives on top of the rock now with 2 huge signs pointing to him saying "free swords" LOL
