### ISSUE TITLE
Check firefox

### ISSUE THREAD

**Issue by nickjanssen** [ironbane/IronbaneServerLegacy#54]

**Comment by bsparks** [comment]
more specifically, there are issues with chat CSS in firefox that don't exist in Chrome.

the font looks different (do we care?)

maybe more...

**Comment by Scottss** [comment]
I went through checking this issue out ant i ran in to a different bug kind of odd. I don't know if it has anything to do with Mozilla or if it was just me. Here it is http://youtu.be/IHKMWM8_yhA

**Comment by nickjanssen** [comment]
Firefox seems to be working fine in 0.4
