### ISSUE TITLE
allow (light) jumping while in water

### ISSUE THREAD

**Issue by nickjanssen** [ironbane/IronbaneServerLegacy#62]

**Comment by ingmargoudt** [comment]
In yesterday's PR I added some code that allows for light jumping (velocity of 0.2 rather than 0.5 normal walking)

**Comment by nickjanssen** [comment]
@ingmargoudt nice work, but there is still an issue with the jump sound being played repeatedly. Could you take a look at that as well?

**Comment by ingmargoudt** [comment]
I will look into this.

**Comment by ingmargoudt** [comment]
I did not have the issue that the jump sound is played repeatedly, but the splash sound is played repeatedly during swimming.. Is that what you mean?

**Comment by nickjanssen** [comment]
@ingmargoudt if you are underwater and press jump it gets played repeatedly
