### ISSUE TITLE
Implement auto-reconnect

### ISSUE THREAD

**Issue by nickjanssen** [ironbane/IronbaneServerLegacy#91]
Socket.io under the hood has already this functionality, which I didn't knew at the time. When the server disconnects, instead of showing the evil error message it should try to automatically reconnect.

**Comment by ingmargoudt** [comment]
io.connect('http://localhost', {
  'reconnect': true,
  'reconnection delay': 500,
  'max reconnection attempts': 10
});

**Comment by ghost** [comment]
This is working, as well. Correct me if I'm wrong, but I'm closing it for now.
