### ISSUE TITLE
some sounds not found even though defined in soundHandler

### ISSUE THREAD

**Issue by nickjanssen** [ironbane/IronbaneServerLegacy#98]
Calling

```
soundHandler.Play("stepWater", this.position);
```

says the sound cannot be found even though it is defined:

```
        "stepWater1": "step/water1.wav",
        "stepWater2": "step/water2.wav",
```

**Comment by ingmargoudt** [comment]
Not a defect. The identifiers that the soundHandler previously used with, dont respond anymore. Instead a sound is triggered on a prefix of any path. For example:

play("step/water"): could play step/water1.mp3 , step/water2.mp3
play("step/"): could player step/water1.mp3, step/water2.mp3, step/wood1.mp3

In this morning's PR I removed the old identifiers from soundHandler

**Comment by ingmargoudt** [comment]
I think this issue can be closed
